version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  # API fora do Docker Compose pois ela vai rodar sem Docker

  otel-collector:
    image: otel/opentelemetry-collector:0.95.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888" 
      - "8889:8889" 
      - "13133:13133"
      - "4317:4317"  # Porta exposta para conexao com sua API
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090  # Porta exposta para acesso externo
    command:
      - '--config.file=/etc/prometheus/prometheus-ws2019.yml'
    volumes:
      - ./config/prometheus-ws2019.yml:/etc/prometheus/prometheus-ws2019.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3000:3000'  # Porta exposta para acesso externo
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring

  windows_exporter:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    container_name: windows_exporter
    build:
      context: .
      dockerfile: config/Dockerfile.ws2019
    ports:
      - '9182:9182'  # Porta exposta para acesso externo
    restart: unless-stopped
    networks:
      - monitoring

