services:
  windows_exporter:
    image: your-windows-exporter-image-w10:latest
    build:
      context: .
      dockerfile: Dockerfile.w10
    ports:
      - "9182:9182"
    networks:
      - monitoring
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  monitoring:
    driver: bridge