global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889'] # OTEL Collector Metrics Exposure
      - targets: ['otel-collector:8888'] # OTEL Collector Prometheus Receiver

  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['localhost:9190'] # Porta padrão = 9182